#!/usr/bin/env python3
import os
import json
import sys
import glob
from datetime import datetime
AIM_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
try:
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown, extract_latest_markdown_export
except ImportError:
    sys.path.append(os.path.join(AIM_ROOT, "scripts"))
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown, extract_latest_markdown_export

# --- CONFIGURATION (Load from core/CONFIG.json) ---
CONFIG_PATH = os.path.join(AIM_ROOT, "core/CONFIG.json")
with open(CONFIG_PATH, 'r') as f:
    CONFIG = json.load(f)

CONTINUITY_DIR = CONFIG['paths']['continuity_dir']
ARCHIVE_RAW_DIR = os.path.join(AIM_ROOT, "archive/raw")

def atomic_write(file_path, content):
    """
    Safely writes content to a file by writing to a temporary file,
    flushing, and then performing an atomic replacement.
    """
    temp_path = f"{file_path}.tmp"
    try:
        with open(temp_path, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        
        # Perform the atomic swap
        os.replace(temp_path, file_path)
    except Exception as e:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise e

def generate_reincarnation_gameplan(user_directive=""):
    """
    Analyzes the full session essence and generates a rigid REINCARNATION_GAMEPLAN.md.
    Uses the user's input as the 'Commander's Intent'.
    """
    print("      Analyzing session heartbeat for Gameplan...")
    clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_CLEAN.md")
    
    session_essence = ""
    if os.path.exists(clean_path):
        with open(clean_path, "r", encoding="utf-8") as f:
            # Read up to 50k characters of the history to capture the arc without blowing context
            session_essence = f.read()[-50000:]
            
    try:
        # Zero API replacement: We parse the logic purely systematically based on user input.
        output_path = os.path.join(CONTINUITY_DIR, "REINCARNATION_GAMEPLAN.md")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        full_gameplan = f"# REINCARNATION GAMEPLAN\n\n"
        full_gameplan += "## ⚠️ URGENT DIRECTIVE FOR THE INCOMING AGENT\n"
        full_gameplan += "You are waking up in the middle of a high-momentum development cycle. "
        full_gameplan += "The previous agent has distilled the session heartbeat into these rigid directives:\n\n"
        
        # Format the intent as rigid bullet points explicitly generated by the architecture
        full_gameplan += f"1. Review `continuity/CURRENT_PULSE.md` to establish the exact procedural edge.\n"
        full_gameplan += f"2. Continue execution targeting the immediate mandate: '{user_directive}'.\n"
        full_gameplan += f"3. Retain complete architectural safety over all GitOps routines.\n"
        
        full_gameplan += f"\n\n---\n**Commander's Intent:** {user_directive}\n"
        full_gameplan += f"**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        
        atomic_write(output_path, full_gameplan)
            
        print(f"      [Success] Gameplan written to: {os.path.basename(output_path)}")
        return True
    except Exception as e:
        print(f"      Gameplan Generation Error: {e}")
        return False

def generate_handoff_pulse():
    """
    Fast, Short-Term Continuity Engine.
    Triggers the Windows desktop UI Hook to pull the chat directly
    from Antigravity, then ingests the 0-token Markdown from Downloads.
    """
    import subprocess
    print("      [A.I.M] Triggering UI OS Handoff sequence...")
    try:
        subprocess.run(["python", os.path.join(AIM_ROOT, "scripts", "auto_export.py")], check=True)
    except Exception as e:
        print(f"      [A.I.M] Warning: auto_export.py failed ({e}). Proceeding with legacy/existing file.")
        
    print("      [A.I.M] Ingesting native OS transcript...")
    transcript = extract_latest_markdown_export()
    
    os.makedirs(CONTINUITY_DIR, exist_ok=True)
    clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_FLIGHT_RECORDER.md")
    atomic_write(clean_path, transcript)

    # --- LITERALLY ZERO-API PROJECT EDGE SYNTHESIS ---
    try:
        now = datetime.now()
        date_str = now.strftime('%Y-%m-%d')
        timestamp_str = now.strftime('%H:%M:%S')
        
        pulse_output = f"---\ndate: {date_str}\ntime: \"{timestamp_str}\"\ntype: handoff\n---\n\n"
        pulse_output += f"# A.I.M. Context Pulse (Zero-Token Native OS Handoff)\n\n"
        
        pulse_output += "### Immediate Hardware State Edge:\n"
        # Extract last ~1000 chars to represent the explicit project edge
        edge_text = transcript[-1000:] if len(transcript) > 1000 else transcript
        pulse_output += f"```markdown\n{edge_text}\n```\n"
        
        pulse_output += "\n\n---\n\"I bypassed the Antigravity backend natively using Win32 Desktop Hooks.\" — **A.I.M.**"
        
        pulse_path = os.path.join(CONTINUITY_DIR, "CURRENT_PULSE.md")
        atomic_write(pulse_path, pulse_output)
            
        # Phase 39: Context Preemption Fix (The Double-Bind Handoff)
        handoff_path = os.path.join(AIM_ROOT, "HANDOFF.md")
        handoff_content = f"""# A.I.M. Continuity Handoff

## ⚠️ CRITICAL INSTRUCTION FOR INCOMING AGENT ⚠️
You are waking up in the middle of a continuous operational loop.
To prevent hallucination, you must establish **Epistemic Certainty** regarding the previous agent's actions before you write any code.

### The Continuity Protocol (The Reincarnation Gameplan)
1. Read `continuity/REINCARNATION_GAMEPLAN.md` (The rigid executive directive passed by the previous agent).
2. Read `continuity/CURRENT_PULSE.md` (The explicit handoff state and project edge).
3. Read `ISSUE_TRACKER.md` (The local ledger of all open and closed tickets).
4. (Optional) Read `continuity/LAST_SESSION_FLIGHT_RECORDER.md` ONLY IF the Gameplan explicitly requires historical context extraction.
5. Do not blindly assume success. Verify the state via file reads or tests.

---
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        atomic_write(handoff_path, handoff_content)
            
        print("      Pulse updated: CURRENT_PULSE.md")
        print("\n\033[92m--- A.I.M. HANDOFF READY ---\033[0m")
        print("To prevent 'Context Preemption' on the next boot, copy and paste this exact prompt:")
        print("\033[93mWake up. 1. Read GEMINI.md and acknowledge your core constraints. 2. Read HANDOFF.md to receive your immediate context and directives.\033[0m\n")

    except Exception as e:
        print(f"      Handoff Generator Error: {e}")

if __name__ == "__main__":
    generate_handoff_pulse()
    # If called with an argument, generate the gameplan too
    if len(sys.argv) > 1:
        generate_reincarnation_gameplan(sys.argv[1])
