#!/usr/bin/env python3
import os
import json
import sys
import glob
from datetime import datetime
AIM_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
try:
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown, extract_latest_markdown_export, parse_markdown_transcript
except ImportError:
    sys.path.insert(0, os.path.join(AIM_ROOT, "scripts"))
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown, extract_latest_markdown_export, parse_markdown_transcript

# --- CONFIGURATION (Load from core/CONFIG.json) ---
CONFIG_PATH = os.path.join(AIM_ROOT, "core/CONFIG.json")
with open(CONFIG_PATH, 'r') as f:
    CONFIG = json.load(f)

CONTINUITY_DIR = CONFIG['paths']['continuity_dir']
ARCHIVE_RAW_DIR = os.path.join(AIM_ROOT, "archive/raw")

def atomic_write(file_path, content):
    """
    Safely writes content to a file by writing to a temporary file,
    flushing, and then performing an atomic replacement.
    """
    temp_path = f"{file_path}.tmp"
    try:
        with open(temp_path, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        
        # Perform the atomic swap
        os.replace(temp_path, file_path)
    except Exception as e:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise e

def generate_reincarnation_gameplan(user_directive=""):
    """
    Analyzes the full session essence and generates a rigid REINCARNATION_GAMEPLAN.md.
    Uses the user's input as the 'Commander's Intent'.
    """
    print("      Analyzing session heartbeat for Gameplan...")
    clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_CLEAN.md")
    
    session_essence = ""
    if os.path.exists(clean_path):
        with open(clean_path, "r", encoding="utf-8") as f:
            # Read up to 50k characters of the history to capture the arc without blowing context
            session_essence = f.read()[-50000:]
            
    try:
        # Zero API replacement: We parse the logic purely systematically based on user input.
        output_path = os.path.join(CONTINUITY_DIR, "REINCARNATION_GAMEPLAN.md")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        full_gameplan = f"# REINCARNATION GAMEPLAN\n\n"
        full_gameplan += "## ⚠️ URGENT DIRECTIVE FOR THE INCOMING AGENT\n"
        full_gameplan += "You are waking up in the middle of a high-momentum development cycle. "
        full_gameplan += "The previous agent has distilled the session heartbeat into these rigid directives:\n\n"
        
        # Format the intent as rigid bullet points explicitly generated by the architecture
        full_gameplan += f"1. Review `continuity/CURRENT_PULSE.md` to establish the exact procedural edge.\n"
        full_gameplan += f"2. Continue execution targeting the immediate mandate: '{user_directive}'.\n"
        full_gameplan += f"3. Retain complete architectural safety over all GitOps routines.\n"
        
        full_gameplan += f"\n\n---\n**Commander's Intent:** {user_directive}\n"
        full_gameplan += f"**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        
        atomic_write(output_path, full_gameplan)
            
        print(f"      [Success] Gameplan written to: {os.path.basename(output_path)}")
        return True
    except Exception as e:
        print(f"      Gameplan Generation Error: {e}")
        return False

def generate_handoff_pulse():
    """
    Fast, Short-Term Continuity Engine.
    Triggers the Windows desktop UI Hook to pull the chat directly
    from Antigravity, then ingests the 0-token Markdown from Downloads.
    """
    import subprocess
    print("      [A.I.M] Triggering UI OS Handoff sequence...")
    try:
        subprocess.run(["python", os.path.join(AIM_ROOT, "scripts", "auto_export.py")], check=True)
    except Exception as e:
        print(f"      [A.I.M] Warning: auto_export.py failed ({e}). Proceeding with legacy/existing file.")
        
    print("      [A.I.M] Ingesting native OS transcript...")
    transcript = extract_latest_markdown_export()
    
    os.makedirs(CONTINUITY_DIR, exist_ok=True)
    os.makedirs(ARCHIVE_RAW_DIR, exist_ok=True)
    clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_FLIGHT_RECORDER.md")
    atomic_write(clean_path, transcript)

    try:
        now = datetime.now()
        timestamp_slug = now.strftime('%Y%m%d_%H%M%S')
        date_str = now.strftime('%Y-%m-%d')
        timestamp_str = now.strftime('%H:%M:%S')

        # --- PIPELINE 1: DEEP MEMORY ARCHIVE & SQLITE ---
        archive_path = os.path.join(ARCHIVE_RAW_DIR, f"session_{timestamp_slug}.md")
        atomic_write(archive_path, transcript)
        
        # Segment into structural dictionaries
        turns = parse_markdown_transcript(transcript)
        
        # SQLite Engram Mirroring
        import sqlite3
        history_dir = os.path.join(AIM_ROOT, "history")
        os.makedirs(history_dir, exist_ok=True)
        db_path = os.path.join(history_dir, "session_engram.db")
        
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        cur.execute('''CREATE TABLE IF NOT EXISTS chat_history 
                       (id INTEGER PRIMARY KEY AUTOINCREMENT, 
                        session_id TEXT, 
                        timestamp TEXT, 
                        role TEXT, 
                        content TEXT)''')
        
        session_id_val = f"session_{timestamp_slug}"
        for turn in turns:
            cur.execute("INSERT INTO chat_history (session_id, timestamp, role, content) VALUES (?, ?, ?, ?)",
                        (session_id_val, now.strftime('%Y-%m-%d %H:%M:%S'), turn['role'], turn['text']))
        conn.commit()
        conn.close()
        print(f"      [A.I.M] Archived {len(turns)} turns to SQLite Engram.")
        
        # --- PIPELINE 4: SINGLE-SHOT MEMORY COMPILER (Issue #55) ---
        try:
            print("      [A.I.M] Engaging Single-Shot Memory Compiler...")
            import sys
            import os
            sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "hooks"))
            from session_summarizer import compile_single_shot
            compile_single_shot(archive_path)
        except Exception as e:
            print(f"      [A.I.M] Warning: Single-Shot Compiler failed ({e}). Non-blocking.")

        # --- PIPELINE 2: ZERO-API PROJECT EDGE SYNTHESIS ---
        pulse_output = f"---\ndate: {date_str}\ntime: \"{timestamp_str}\"\ntype: handoff\n---\n\n"
        pulse_output += f"# A.I.M. Context Pulse (Zero-Token Native OS Handoff)\n\n"
        
        pulse_output += "### Immediate Hardware State Edge (Last 5 Exchanges):\n"
        
        edge_turns = turns[-5:]
        for et in edge_turns:
            pulse_output += f"**[{et['role']}]**:\n```markdown\n{et['text']}\n```\n\n"
        
        pulse_output += "\n---\n\"I bypassed the Antigravity backend natively using Win32 Desktop Hooks.\" — **A.I.M.**"
        
        pulse_path = os.path.join(CONTINUITY_DIR, "CURRENT_PULSE.md")
        atomic_write(pulse_path, pulse_output)
            
        # Phase 39: Context Preemption Fix (The Double-Bind Handoff)
        handoff_path = os.path.join(AIM_ROOT, "HANDOFF.md")
        handoff_content = f"""# A.I.M. Continuity Handoff

## ⚠️ CRITICAL INSTRUCTION FOR INCOMING AGENT ⚠️
You are waking up in the middle of a continuous operational loop.
To prevent hallucination, you must establish **Epistemic Certainty** regarding the previous agent's actions before you write any code.

### The Continuity Protocol (The Reincarnation Gameplan)
1. Read `continuity/REINCARNATION_GAMEPLAN.md` (The rigid executive directive passed by the previous agent).
2. Read `continuity/CURRENT_PULSE.md` (The explicit handoff state and project edge).
3. Read `ISSUE_TRACKER.md` (The local ledger of all open and closed tickets).
4. (Optional) Read `continuity/LAST_SESSION_FLIGHT_RECORDER.md` ONLY IF the Gameplan explicitly requires historical context extraction.
5. Do not blindly assume success. Verify the state via file reads or tests.

---
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        atomic_write(handoff_path, handoff_content)
            
        print("      Pulse updated: CURRENT_PULSE.md")
        print("\n\033[92m--- A.I.M. HANDOFF READY ---\033[0m")
        print("To prevent 'Context Preemption' on the next boot, copy and paste this exact prompt:")
        print("\033[93mWake up. 1. Read GEMINI.md and acknowledge your core constraints. 2. Read HANDOFF.md to receive your immediate context and directives.\033[0m\n")

    except Exception as e:
        print(f"      Handoff Generator Error: {e}")

if __name__ == "__main__":
    generate_handoff_pulse()
    # If called with an argument, generate the gameplan too
    if len(sys.argv) > 1:
        generate_reincarnation_gameplan(sys.argv[1])
