#!/usr/bin/env python3
import os
import json
import sys
import glob
from datetime import datetime
AIM_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
try:
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown
except ImportError:
    sys.path.append(os.path.join(AIM_ROOT, "scripts"))
    from extract_signal import extract_signal, extract_signal_from_txt, extract_signal_from_antigravity_steps, skeleton_to_markdown

# --- CONFIGURATION (Load from core/CONFIG.json) ---
CONFIG_PATH = os.path.join(AIM_ROOT, "core/CONFIG.json")
with open(CONFIG_PATH, 'r') as f:
    CONFIG = json.load(f)

CONTINUITY_DIR = CONFIG['paths']['continuity_dir']
ARCHIVE_RAW_DIR = os.path.join(AIM_ROOT, "archive/raw")

def atomic_write(file_path, content):
    """
    Safely writes content to a file by writing to a temporary file,
    flushing, and then performing an atomic replacement.
    """
    temp_path = f"{file_path}.tmp"
    try:
        with open(temp_path, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        
        # Perform the atomic swap
        os.replace(temp_path, file_path)
    except Exception as e:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise e

def generate_reincarnation_gameplan(user_directive=""):
    """
    Analyzes the full session essence and generates a rigid REINCARNATION_GAMEPLAN.md.
    Uses the user's input as the 'Commander's Intent'.
    """
    print("      Analyzing session heartbeat for Gameplan...")
    clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_CLEAN.md")
    
    session_essence = ""
    if os.path.exists(clean_path):
        with open(clean_path, "r", encoding="utf-8") as f:
            # Read up to 50k characters of the history to capture the arc without blowing context
            session_essence = f.read()[-50000:]
            
    try:
        # Zero API replacement: We parse the logic purely systematically based on user input.
        output_path = os.path.join(CONTINUITY_DIR, "REINCARNATION_GAMEPLAN.md")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        full_gameplan = f"# REINCARNATION GAMEPLAN\n\n"
        full_gameplan += "## ⚠️ URGENT DIRECTIVE FOR THE INCOMING AGENT\n"
        full_gameplan += "You are waking up in the middle of a high-momentum development cycle. "
        full_gameplan += "The previous agent has distilled the session heartbeat into these rigid directives:\n\n"
        
        # Format the intent as rigid bullet points explicitly generated by the architecture
        full_gameplan += f"1. Review `continuity/CURRENT_PULSE.md` to establish the exact procedural edge.\n"
        full_gameplan += f"2. Continue execution targeting the immediate mandate: '{user_directive}'.\n"
        full_gameplan += f"3. Retain complete architectural safety over all GitOps routines.\n"
        
        full_gameplan += f"\n\n---\n**Commander's Intent:** {user_directive}\n"
        full_gameplan += f"**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        
        atomic_write(output_path, full_gameplan)
            
        print(f"      [Success] Gameplan written to: {os.path.basename(output_path)}")
        return True
    except Exception as e:
        print(f"      Gameplan Generation Error: {e}")
        return False

def generate_handoff_pulse():
    """
    Fast, Short-Term Continuity Engine.
    Reads the latest overview.txt transcript natively from the Antigravity backend,
    extracts the signal via Python iteration, and zeroes the API cost.
    """
    brain_dir = os.path.expanduser(r"~\.gemini\antigravity\brain")
    if not os.path.exists(brain_dir):
        brain_dir = r"C:\Users\kingb\.gemini\antigravity\brain"
        
    try:
        dirs = [os.path.join(brain_dir, d) for d in os.listdir(brain_dir) if os.path.isdir(os.path.join(brain_dir, d))]
        if not dirs:
            return
        latest_dir = max(dirs, key=os.path.getmtime)
    except Exception as e:
        print(f"Handoff Generator: Directory scan error: {e}")
        return

    latest_transcript = os.path.join(latest_dir, ".system_generated", "logs", "overview.txt")
    
    try:
        if not os.path.exists(latest_transcript):
            print(f"Handoff Generator: overview.txt not flushed. Executing dynamic active-state extraction from steps...")
            skeleton = extract_signal_from_antigravity_steps(latest_dir)
        else:
            skeleton = extract_signal_from_txt(latest_transcript)
            
        # Write clean session artifact (Rolling Delta or Full History)
        os.makedirs(CONTINUITY_DIR, exist_ok=True)
        clean_path = os.path.join(CONTINUITY_DIR, "LAST_SESSION_FLIGHT_RECORDER.md")
        
        # Convert JSON skeleton into pure Markdown dialogue
        session_id = os.path.basename(latest_transcript).replace('.json', '') if os.path.exists(latest_transcript) else os.path.basename(latest_dir)
        md_content = skeleton_to_markdown(skeleton, session_id)
        
        # Load configurable line limit, default to 0 (Full History)
        tail_lines = CONFIG.get('settings', {}).get('handoff_context_lines', 0)
        
        if tail_lines > 0:
            md_lines = md_content.splitlines()
            if len(md_lines) > tail_lines:
                truncated_lines = md_lines[-tail_lines:]
            else:
                truncated_lines = md_lines
                
            clean_content = "# A.I.M. Session Flight Recorder (Rolling Delta)\n"
            clean_content += f"*This is a noise-reduced flight recorder showing only the last {tail_lines} lines. NOT automatically injected into LLM context.*\n\n"
            clean_content += '\n'.join(truncated_lines) + '\n'
            atomic_write(clean_path, clean_content)
        else:
            clean_content = "# A.I.M. Session Flight Recorder (Full History)\n"
            clean_content += f"*This is a noise-reduced flight recorder showing the entire session. NOT automatically injected into LLM context.*\n\n"
            clean_content += md_content + '\n'
            atomic_write(clean_path, clean_content)
                
        # --- PROJECT EDGE SYNTHESIS (High Fidelity) ---
        # Capture only the last 10 turns of the filtered signal to identify the "Technical Edge"
        # without polluting the context with the entire session history.
        recent_skeleton = skeleton[-10:] if isinstance(skeleton, list) else skeleton
        context_str = json.dumps(recent_skeleton, indent=2)

    except Exception as e:
        print(f"Handoff Generator: Signal extraction failure on {latest_transcript}: {e}")
        return

    # --- LITERALLY ZERO-API PROJECT EDGE SYNTHESIS ---
    try:
        now = datetime.now()
        date_str = now.strftime('%Y-%m-%d')
        timestamp_str = now.strftime('%H:%M:%S')
        
        pulse_output = f"---\ndate: {date_str}\ntime: \"{timestamp_str}\"\ntype: handoff\n---\n\n"
        pulse_output += f"# A.I.M. Context Pulse (Extracted by Zero-Token Backend Architecture)\n\n"
        
        # Map recent trajectory inherently from the skeleton tools
        recent_skeleton = skeleton[-10:] if isinstance(skeleton, list) else []
        tool_metrics = [t.get('text', '') for t in recent_skeleton if 'SYSTEM TOOL CALL' in t.get('text', '')]
        pulse_output += "### Immediate Hardware State Edge:\n"
        for idx, tool in enumerate(tool_metrics[-5:]):
             pulse_output += f"- {tool}\n"
             
        pulse_output += "\n\n---\n\"I explicitly executed identically without relying on a Large Language Model routing call.\" — **A.I.M. (Rigid Zero-Token Backend Pulse)**"
        
        pulse_path = os.path.join(CONTINUITY_DIR, "CURRENT_PULSE.md")
        atomic_write(pulse_path, pulse_output)
            
        # Phase 39: Context Preemption Fix (The Double-Bind Handoff)
        handoff_path = os.path.join(AIM_ROOT, "HANDOFF.md")
        handoff_content = f"""# A.I.M. Continuity Handoff

## ⚠️ CRITICAL INSTRUCTION FOR INCOMING AGENT ⚠️
You are waking up in the middle of a continuous operational loop.
To prevent hallucination, you must establish **Epistemic Certainty** regarding the previous agent's actions before you write any code.

### The Continuity Protocol (The Reincarnation Gameplan)
1. Read `continuity/REINCARNATION_GAMEPLAN.md` (The rigid executive directive passed by the previous agent).
2. Read `continuity/CURRENT_PULSE.md` (The explicit handoff state and project edge).
3. Read `ISSUE_TRACKER.md` (The local ledger of all open and closed tickets).
4. (Optional) Read `continuity/LAST_SESSION_FLIGHT_RECORDER.md` ONLY IF the Gameplan explicitly requires historical context extraction.
5. Do not blindly assume success. Verify the state via file reads or tests.

---
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        atomic_write(handoff_path, handoff_content)
            
        print("      Pulse updated: CURRENT_PULSE.md")
        print("\n\033[92m--- A.I.M. HANDOFF READY ---\033[0m")
        print("To prevent 'Context Preemption' on the next boot, copy and paste this exact prompt:")
        print("\033[93mWake up. 1. Read GEMINI.md and acknowledge your core constraints. 2. Read HANDOFF.md to receive your immediate context and directives.\033[0m\n")

    except Exception as e:
        print(f"      Handoff Generator Error: {e}")

if __name__ == "__main__":
    generate_handoff_pulse()
    # If called with an argument, generate the gameplan too
    if len(sys.argv) > 1:
        generate_reincarnation_gameplan(sys.argv[1])
